apiVersion: v1
kind: Service
metadata:
  name: openmrs-distro-svc
spec:
  selector:
    app: openmrs-distro
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: openmrs-distro-config
data:
  DB_AUTO_UPDATE: "false"
  DB_CREATE_TABLES: "false"
  DB_HOST: mysql-svc
  MODULE_WEB_ADMIN: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openmrs-distro-deployment
  labels:
    app: openmrs-distro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openmrs-distro
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: openmrs-distro
    spec:
      containers:
        - name: openmrs-distro
          image: openmrs-distro:1
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: openmrs-distro-config
          env:
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: openmrs-distro-db-secrets
                  key: MYSQL_DATABASE
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: openmrs-distro-db-secrets
                  key: MYSQL_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: openmrs-distro-db-secrets
                  key: MYSQL_PASSWORD
          resources:
            limits:
              memory: 2048Mi
            requests:
              memory: 1024Mi
