apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
spec:
  clusterIP: None
  ports:
    - port: 3306
      protocol: TCP
  selector:
    app: mysql
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-data-pv-claim
  labels:
    app: mysql
spec:
  storageClassName: standard
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: openmrs-db:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3306
          args:
            - mysqld
            - --character-set-server=utf8
            - --collation-server=utf8_general_ci
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: openmrs-distro-db-secrets
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: openmrs-distro-db-secrets
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: openmrs-distro-db-secrets
                  key: MYSQL_PASSWORD
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: openmrs-distro-db-secrets
                  key: MYSQL_ROOT_PASSWORD
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-data
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-data-pv-claim
